import {StyleSheet} from 'react-native';
import {colors, width} from '@constants';

export default StyleSheet.create({
  flexContainer: {
    flex: 1,
  },
  modal: {
    flex: 1,
    justifyContent: 'flex-start',
    margin: 0,
  },
  modalHeaderContainer: {
    paddingTop: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    zIndex: 5,
  },
  title: {
    color: colors.white_FFFFFF,
    fontWeight: '600',
    marginLeft: 24 + 16, // with icon + left padding
    flexGrow: 1,
    textAlign: 'center',
  },
  iconClose: {
    marginRight: 16,
  },
  focusContainer: {
    flex: 1,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  innerFocusContainer: {
    padding: 20,
    position: 'absolute',
    width: width - 44 * 2,
    height: width - 44 * 2,
  },
  focusLeftTopCorner: {
    borderLeftWidth: 4,
    borderTopWidth: 4,
    borderColor: colors.green_secondary_55C977,
    position: 'absolute',
    left: 0,
    top: 0,
    width: 44,
    height: 44,
    backgroundColor: 'transparent',
    zIndex: 10,
  },
  focusRightTopCorner: {
    borderRightWidth: 4,
    borderTopWidth: 4,
    borderColor: colors.green_secondary_55C977,
    position: 'absolute',
    right: 0,
    top: 0,
    width: 44,
    height: 44,
    backgroundColor: 'transparent',
    zIndex: 10,
  },
  focusLeftBottomCorner: {
    borderLeftWidth: 4,
    borderBottomWidth: 4,
    borderColor: colors.green_secondary_55C977,
    position: 'absolute',
    left: 0,
    bottom: 0,
    width: 44,
    height: 44,
    backgroundColor: 'transparent',
    zIndex: 10,
  },
  focusRightBottomCorner: {
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderColor: colors.green_secondary_55C977,
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 44,
    height: 44,
    backgroundColor: 'transparent',
    zIndex: 10,
  },
});
